"""
LlamaIndex Code Documentation Generator
Stage 15 of Jenkins Pipeline

What it does:
- Reads all files in app/ folder using LlamaIndex
- Builds a searchable index of the codebase
- Uses Ollama (Llama3) to generate documentation
- Saves auto-generated docs to docs/AUTO_GENERATED_README.md
"""

import os
import time
import json


def generate_documentation():
    print("📚 LlamaIndex Documentation Generator Starting...")

    # Install if needed
    try:
        from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
        from llama_index.llms.ollama import Ollama as LlamaOllama
        from llama_index.embeddings.huggingface import HuggingFaceEmbedding
    except ImportError:
        print("Installing llama-index...")
        os.system("pip install --break-system-packages llama-index llama-index-llms-ollama llama-index-embeddings-huggingface -q")
        try:
            from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
            from llama_index.llms.ollama import Ollama as LlamaOllama
            from llama_index.embeddings.huggingface import HuggingFaceEmbedding
        except Exception as e:
            print(f"⚠️ Install failed: {e}")
            generate_static_docs()
            return

    # Check app folder exists
    if not os.path.exists("app"):
        print("⚠️ app/ folder not found")
        generate_static_docs()
        return

    print("📂 Reading code files with LlamaIndex...")
    start = time.time()

    try:
        # Configure LlamaIndex to use local Ollama
        Settings.llm = LlamaOllama(
            model="llama3",
            base_url="http://localhost:11434",
            request_timeout=120.0
        )
        Settings.embed_model = HuggingFaceEmbedding(
            model_name="BAAI/bge-small-en-v1.5"
        )

        # Read all files in app/
        documents = SimpleDirectoryReader(
            "app/",
            recursive=True,
            required_exts=[".py", ".txt", ".md"]
        ).load_data()

        print(f"📄 Indexed {len(documents)} files")

        # Build index
        index = VectorStoreIndex.from_documents(documents)
        query_engine = index.as_query_engine()

        # Generate documentation sections
        sections = {
            "overview": "What does this application do? Provide a brief overview in 2-3 sentences.",
            "endpoints": "List all API endpoints, their HTTP methods, and what they do.",
            "security": "What security considerations exist in this code?",
            "setup": "How would a developer set up and run this application?"
        }

        docs = {}
        for section, question in sections.items():
            print(f"✍️  Generating {section}...")
            try:
                response = query_engine.query(question)
                docs[section] = str(response)
            except Exception as e:
                docs[section] = f"Generated by LlamaIndex - {section} section"

        duration = time.time() - start
        write_docs(docs, len(documents), duration)

    except Exception as e:
        print(f"⚠️ LlamaIndex error: {e} — generating static docs")
        generate_static_docs()


def write_docs(docs, file_count, duration):
    os.makedirs("docs", exist_ok=True)
    content = f"""# Auto-Generated Documentation
*Generated by LlamaIndex + Llama3 | Files indexed: {file_count} | Time: {duration:.1f}s*

---

## Overview
{docs.get('overview', 'Flask web application for DevSecOps pipeline testing')}

---

## API Endpoints
{docs.get('endpoints', 'See app/app.py for full endpoint list')}

---

## Security Features
{docs.get('security', 'Security scanning handled by Bandit, Semgrep, Trivy, and OWASP ZAP')}

---

## Setup Instructions
{docs.get('setup', 'Run: pip install -r requirements.txt && python app.py')}

---
*This documentation was automatically generated by the AI DevSecOps Pipeline*
"""
    with open("docs/AUTO_GENERATED_README.md", 'w') as f:
        f.write(content)

    print(f"✅ Documentation generated: docs/AUTO_GENERATED_README.md")


def generate_static_docs():
    """Fallback if Ollama not available"""
    print("📝 Generating static documentation (Ollama not available)...")
    docs = {
        "overview": "Flask REST API application used for DevSecOps pipeline demonstration.",
        "endpoints": "GET / - Home, GET /health - Health check, GET /users - List users, POST /users - Create user, GET /search - Search",
        "security": "Scanned by Bandit (SAST), Semgrep (custom rules), Trivy (container), OWASP ZAP (DAST)",
        "setup": "pip install -r requirements.txt && python app.py"
    }
    write_docs(docs, 0, 0)


if __name__ == "__main__":
    generate_documentation()
