replicaCount: 2

image:
  repository: "devsecops-app"
  tag: "local"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

securityContext:
  runAsNonRoot: true
  runAsUser: 10001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  path: /health
  port: 5000
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: app.3-7-244-169.sslip.io
      paths:
        - path: /

networkPolicy:
  enabled: true
  ingressNamespaces:
    - ingress-nginx
    - monitoring
